### ISSUE TITLE
raster (blue dot) is missing from the figure in README

### ISSUE THREAD

**Issue by Nowosad** [kadyb/raster-benchmark#12]

**Comment by kadyb** [comment]
R packages are represented by triangles and Python packages by circles, so `{raster}` is represented by a blue triangle. In 950f787, I changed the color representations of the packages to squares (instead of circles), so the figure should be clearer. I will update the figure in the README as I perform the tests in the near future.

**Comment by Nowosad** [comment]
Oh, now I understand. 

I do not know how to reproduce this figure, but would not it be possible to have both circles and triangles on the color legend?

**Comment by kadyb** [comment]
> I do not know how to reproduce this figure

The easiest way to reproduce is to run `run_benchmarks.sh` first - then csv files with timings will be created. The figure is generated from R Notebook `report.Rmd`, but you must manually run chunk named `final-plot` (line 174).

> but would not it be possible to have both circles and triangles on the color legend?

Yeah, this is the best option, but I don't know if `{ggplot2}` works that way. I currently use point geometry with two shapes (circles and triangles), but `{ggplot2}` automatically only shows circles in the legend. In this line of code:

https://github.com/kadyb/raster-benchmark/blob/950f78703ff05f53a8962612c027ba80574743db/report.Rmd#L189

I don't know if a legend can contain different shapes at the same time.
